# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirtop < Formula
  desc "Real-time terminal dashboard for monitoring directory stats."
  homepage "https://github.com/arthurrio/dirtop"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.1.0/dirtop_darwin_amd64.tar.gz"
      sha256 "028a0b3159e3a8322d57b72de7610fb25f6e6df916c13ad18fd3325c674179cf"

      define_method(:install) do
        bin.install "dirtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.1.0/dirtop_darwin_arm64.tar.gz"
      sha256 "bca04330ac54cae66cdcddf1b36c2e5777b180c6b0732130499a00c181be8b46"

      define_method(:install) do
        bin.install "dirtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.1.0/dirtop_linux_amd64.tar.gz"
      sha256 "3253ac9ca263e8bac0fcf320b33ccdfc9d2f3ca861e300f81ba732967e10e846"
      define_method(:install) do
        bin.install "dirtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.1.0/dirtop_linux_arm64.tar.gz"
      sha256 "6d723c5115a2e45626ab188df02bdaf7d6cf14d1512c7d913b4f3fb735cbd05f"
      define_method(:install) do
        bin.install "dirtop"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dirtop -version")
  end
end
