# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dirtop < Formula
  desc "Real-time terminal dashboard for monitoring directory stats."
  homepage "https://github.com/arthurrio/dirtop"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.2.0/dirtop_darwin_amd64.tar.gz"
      sha256 "aad9501c005cb0eec0e8fe15937e7f02ee60788decc33d0f33a7c5e30c974213"

      define_method(:install) do
        bin.install "dirtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.2.0/dirtop_darwin_arm64.tar.gz"
      sha256 "6f25df49b7cbd53937d03c09c440a807606dab5bc234b5f6b3b04f0453d9dcf5"

      define_method(:install) do
        bin.install "dirtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.2.0/dirtop_linux_amd64.tar.gz"
      sha256 "dca5d5e03712fca2c7d985a8f57426bc1a1022c6d52a7aff972b3ce401fa0c4c"
      define_method(:install) do
        bin.install "dirtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arthurrio/dirtop/releases/download/v0.2.0/dirtop_linux_arm64.tar.gz"
      sha256 "abfb405b64c63a4e1732ac4e3e5d7929b93fd741932025b81a43effe7d4d5da0"
      define_method(:install) do
        bin.install "dirtop"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dirtop -version")
  end
end
